[tool.poetry]
name = "sentiment"
version = "0.1.0"
description = ""
authors = ["<dmitry.shibanov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
